### ISSUE TITLE
django.utils.six library is deprecated since Django 3.x

### ISSUE THREAD

**Issue by Wired95** [renskiy/django-bitmask-field#7]
Hi!

While the Django requirement is set to `Django 1.8+`, will Django 3.x be supported?

For Django versions older than 3.x it's giving me this error:

```
$ python3 manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/nicolas/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/nicolas/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/nicolas/.local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/nicolas/.local/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/nicolas/.local/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nicolas/Repositories/aae-escom-site/applications/carrers/models/__init__.py", line 1, in <module>
    from .resumee import * 
  File "/home/nicolas/Repositories/aae-escom-site/applications/carrers/models/resumee.py", line 4, in <module>
    from django_bitmask_field import BitmaskField
  File "/home/nicolas/.local/lib/python3.7/site-packages/django_bitmask_field.py", line 8, in <module>
    from django.utils.six import integer_types, buffer_types, text_type
ModuleNotFoundError: No module named 'django.utils.six'
```

As stated in the Django doc [Django doc](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis):
> django.utils.six - Remove usage of this vendored library or switch to six.

Minimal code to reproduce:

```
from django_bitmask_field import BitmaskField
```

```
$ python3 --version
Python 3.7.3
```

```
$ python3 manage.py version
3.0.8
```

Regards and good luck!

**Comment by Wired95** [comment]
Edit: did not see the PR about this error : https://github.com/renskiy/django-bitmask-field/pull/6

**Comment by renskiy** [comment]
@Wired95 thanks for your observation. Will fix it in near future.
